// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1630378295);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1630378358);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.migration.version", 116);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1630378295);
user_pref("browser.search.region", "BR");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[]},\"seen\":[\"save-to-pocket-button\"],\"dirtyAreaCache\":[],\"currentVersion\":17,\"newElementCount\":0}");
user_pref("distribution.iniFile.exists.appversion", "91.0.2");
user_pref("distribution.iniFile.exists.value", false);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210823123856");
user_pref("extensions.lastAppVersion", "91.0.2");
user_pref("extensions.lastPlatformVersion", "91.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"22cda01a-ce60-4cc3-ac5a-0ae7f63ec8fc\",\"formautofill@mozilla.org\":\"934dd9cf-ad25-408e-92bf-696492631740\",\"pictureinpicture@mozilla.org\":\"ecaba8d1-e226-400e-b5e3-b157b5245bd9\",\"screenshots@mozilla.org\":\"96804ca4-6ea9-4315-8190-a7305169fb5f\",\"webcompat-reporter@mozilla.org\":\"a1b2e3b7-bf2c-45b4-8ecc-f67331d4ef05\",\"webcompat@mozilla.org\":\"9338d1da-7172-49a1-893b-9a0e98c8005a\",\"default-theme@mozilla.org\":\"549196d0-058f-43f3-9890-3f5b09ea7f10\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("nimbus.syncdefaultsstore.upgradeDialog", "{\"slug\":\"upgradeDialog-defaultEnabled\",\"enabled\":true,\"targeting\":\"true\",\"variables\":{},\"description\":\"Turn on upgradeDialog by default for all users\"}");
user_pref("pdfjs.enabledCache.state", true);
user_pref("security.sandbox.content.tempDirSuffix", "c8ec8973-4697-4146-a056-20d645663e6e");
user_pref("toolkit.startup.last_success", 1630378357);
user_pref("toolkit.telemetry.cachedClientID", "21b65825-f6ed-4ef3-b03f-37436ad2e143");
user_pref("toolkit.telemetry.previousBuildID", "20210823123856");
